# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /home/jim0228/sta # dataset root dir
train: images/sta_train.txt
val: images/sta_val.txt

# Classes
names:
  0: artwork_(art,_draw,_drawing,_painting,_sketch)
  1: bag_(bag,_grocery,_nylon,_polythene,_pouch,_sachet,_sack,_suitcase)
  2: ball_(ball,_baseball,_basketball)
  3: bicycle_(bicycle,_bike)
  4: book_(book,_booklet,_magazine,_manual,_notebook,_novel,_page,_textbook)
  5: bottle_(bottle,_flask)
  6: bowl
  7: brick
  8: broom_(broom,_broomstick)
  9: brush
  10: bucket
  11: cabinet_(cabinet,_compartment,_cupboard)
  12: caliper
  13: car_(car,_vehicle)
  14: cement_(cement,_concrete,_mortar)
  15: computer_(computer,_ipad,_laptop,_motherboard,_screen)
  16: container_(box,_can,_carton,_case,_casing,_container,_crate,_holder,_jar,_jerrycan,_keg,_pack,_package,_packaging,_packet,_storage,_tank,_tin)
  17: cooker
  18: cup_(cup,_mug,_tumbler)
  19: cutter_(tool)
  20: door
  21: dough
  22: drawer
  23: drill_(drill,_driller)
  24: dumbbell
  25: engine_(assembly,_carburetor,_engine,_motor)
  26: faucet_(faucet,_tap)
  27: floor_(floor,_ground)
  28: flower
  29: food
  30: fridge_(fridge,_refrigerator)
  31: glass
  32: glue_(adhesive,_glue,_gum,_sealant)
  33: hammer_(hammer,_mallet)
  34: garment
  35: jug
  36: knife_(knife,_machete)
  37: lid_(cap,_cover,_lid)
  38: mask
  39: mat_(mat,_rug)
  40: metal_(lead,_metal,_steel)
  41: mold_(mold,_molder,_mould)
  42: mop
  43: mower_(lawnmower,_mower)
  44: napkin_(handkerchief,_napkin,_serviette,_tissue,_wipe)
  45: needle_(hook,_needle)
  46: nut_(tool)
  47: paint
  48: pan_(frypan,_pan,_saucepan)
  49: paper_(chart,_craft,_newspaper,_note,_paper,_papercraft,_poster,_receipt)
  50: pedal
  51: pen_(marker,_pen)
  52: phone_(cellphone,_phone,_smartphone)
  53: plant
  54: plate_(dish,_plate,_platter,_saucer)
  55: playing_cards
  56: pot
  57: pump
  58: rod_(dipstick,_rod,_rod_metal,_shaft)
  59: rope
  60: rubber_band
  61: saw_(chainsaw,_saw,_hacksaw)
  62: scissors
  63: screw_(bolt,_nail,_screw)
  64: screwdriver
  65: shelf
  66: shoe_(boot,_sandal,_shoe,_slipper)
  67: sickle
  68: sieve_(sieve,_strainer)
  69: spatula
  70: sponge_(scrubber,_sponge)
  71: spoon
  72: stone_(rock,_stone)
  73: string_(bobbin,_knot,_lace,_ribbon,_spool,_strand,_string,_thread,_twine,_wool,_yarn)
  74: table_(stand,_table)
  75: tablet
  76: tape_measure_(measure,_measurement)
  77: tile
  78: towel
  79: trash
  80: tray
  81: vegetable_fruit
  82: wall
  83: wheel
  84: wire_(adapter,_cable,_charger,_connector,_cord,_wire)
  85: wood_(fiber,_firewood,_floorboard,_log,_lumber,_plank,_plywood,_timber,_wood,_woodcraft,_woodwork)
  86: wrench
  87: axe
  88: chair
  89: chip_(wood'_metal),
  90: chopping_board
  91: chopstick
  92: fork
  93: glove
  94: hanger
  95: hose
  96: ice
  97: ladder
  98: lever
  99: lubricant_(grease,_lubricant)
  100: nail_polish
  101: nut_(food)
  102: oven
  103: palette
  104: plier
  105: puzzle_or_game_piece_(chess,_domino,_jenga,_jigsaw,_pawn,_puzzle)
  106: rack
  107: radio
  108: remote_control_(control,_remote)
  109: ruler_(rule,_ruler)
  110: sander
  111: sandpaper
  112: scraper_(scraper,_scrapper)
  113: seasoning_(salt,_seasoning,_shaker,_spice,_sugar)
  114: sewing_machine
  115: shears
  116: shovel_(hoe,_shovel,_spade)
  117: sink_(basin,_sink)
  118: solder_iron
  119: spacer
  120: spray_(spray,_sprayer)
  121: tape_(cellotape,_sellotape,_tape)
  122: toy_(doll,_toy)
  123: trowel
  124: vacuum_cleaner
  125: water
  126: weighing_scale
  127: wrapper_(covering,_film,_seal,_wrap,_wrapper,_wrapping)
